[package]
name = "rust-mccv"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_esplora = { version = "0.19.0", default-features = false, features = ["std", "blocking", "blocking-https"] }
bdk_wallet = { version = "1.0.0-beta.5", features = ["rusqlite"] }
bitcoin = { version = "0.32", features = ["serde"] }
#bitcoin = { version = "0.30", features = ["serde"] } # Match bdk
bitcoin_hashes = "0.15.0"
clap = { version = "4.5.21", features = ["derive"] }
rand = "0.8.5"
rayon = "1.10.0"
rusqlite = "0.31"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"

[dev-dependencies]
electrsd = "0.29.0"
serde_json = "1.0.133"
